### ISSUE TITLE
Finder got an error: Handler can’t handle objects of this class. (-10010)

### ISSUE THREAD

**Issue by Fujiwara-Chika** [nimatrueway/mpv-locatefile-lua-script#5]
OS: macOS Mojave 10.14.6 18G9323
MPV 0.33.1
```
[locatefile] File detected '11095193_p0.jpg', your OS file browser will be launched.
[locatefile] macOS detected.
[locatefile] Command to be executed: 'osascript -e 'tell application "Finder"' -e 'set frontmost to true' -e 'reveal (POSIX file "11095193_p0.jpg")' -e 'end tell''
48:85: execution error: Finder got an error: Handler can’t handle objects of this class. (-10010)
```

**Comment by nimatrueway** [comment]
The reason is a filename (without absolute path) was passed to `mpv` as argument, and `mp.get_property("path")` did not return the absolute path of the file. In the end `Finder` can't locate file in current condition.

**Comment by nimatrueway** [comment]
This is a corner case. I'll try to find a way to fix it.

**Comment by Fujiwara-Chika** [comment]
https://stackoverflow.com/questions/7652928/launch-finder-window-with-specific-files-selected/68443482#68443482
Maybe this can help.

**Comment by nimatrueway** [comment]
I found some free time today and normalized path; please give the latest version of script a try and close the ticket if the issue has been resolved for you.

**Comment by Fujiwara-Chika** [comment]
It works, although logs still show the same error. Thank you!
